[package]
name = "packer"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
toml = "0.8.10"
serde = { version = "1.0", features = ["derive"] }
aws-sdk-s3 = "0.31.0"
tokio = { version = "1", features = ["full"] }
